apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp-deploy
  labels:
    app: vproapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: appcontainer
          image: nginx:1.25
          ports:
            - containerPort: 80
