apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: host-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: host-storage
      hostPath:
        path: /mnt/data           # path on the node
        type: DirectoryOrCreate
